version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlite:///users.db
  db:
    image: sqlite:latest
    volumes:
      - ./users.db:/app/users.db
